package main

var answers = [][]string{{"NAPOLEON", "DOCTOR STRANGE", "GATHERER CHILDREN", "RED DIESEL"},
	{"LATE ONSET", "GOOD FAT", "DARN IT ALL", "NET LOSSES"},
	{"LULLABY", "TASTINESS", "DEPARTMENT OF MAGICAL LAW ENFORCEMENT", "DRESS CODE"},
	{"LULLABY", "??", "TINFOIL", "HABITUAL"},
	{"END LOADED", "BITE MARK", "UNDOING", "BASIC"},
	{"ANGLE BRACKETS", "BUDAPEST", "PAISLEY", "FANG"},
	{"STOWING", "WHITE", "RED DIESEL", "NET LOSSES"},
	{"BITE MARK", "HOSPITAL BENEFITS", "PAISLEY", "BASIC"},
	{"BUDAPEST", "??", "CHASKA", "BASIC"},
	{"MILO READY-TO-DRINK", "DISTINCT FEATURES", "ANIME", "LA DODGERS"},
	{"FUEGO", "ANGLE BRACKETS", "HOSPITAL BENEFITS", "ARCHIVED EDITIONS"},
	{"ATE DINNER", "COSMOPOLITAN", "GIANT GROWTH", "FAX"},
	{"BOAT RIDE", "ANIME", "MARCO REUS", "THE XX"},
	{"CALANTHE", "??", "LA DODGERS", "DEFY"}}

func main() {
	
}
